services:
  neo4j:
    image: neo4j:4.2.5
    ports:
      - 7474:7474
      - 7687:7687
      - 7473:7473
    volumes:
      - ~/neo4j/data:/data
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_connector_http_advertised__address: "localhost:7474"
      NEO4J_dbms_connector_bolt_advertised__address: "localhost:7687"
#      NEO4J_dbms_connector_bolt_tls__level: "OPTIONAL"
version: "3"
